services:
    - type: web
      name: your-app-name
      env: python
      plan: free
      buildCommand: "./build.sh"
      startCommand: "python manage.py migrate && gunicorn rbproduct.wsgi --bind 0.0.0.0:$PORT"
      envVars:
          - key: DATABASE_URL
            fromDatabase:
                name: your-db-name
                property: connectionString
          - key: SECRET_KEY
            generateValue: true
          - key: WEB_CONCURRENCY
            value: 4
