# Generated by Django 5.2.5 on 2025-09-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='size_with_price',
        ),
        migrations.AddField(
            model_name='customorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customorder',
            name='owner_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='reference_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='status',
            field=models.CharField(blank=True, choices=[('canceled', 'Canceled'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customorder',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
    ]
