# Generated by Django 5.2.5 on 2025-09-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_customorder_size_with_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customorder',
            old_name='owner_notes',
            new_name='admin_notes',
        ),
    ]
