# Generated by Django 5.2.5 on 2025-09-26 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_owner_notes_customorder_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customorder',
            name='contact_method',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('phone', 'Phone'), ('email', 'Email')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.CreateModel(
            name='CustomOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='custom_orders/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='custom_orders/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('custom_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.customorder')),
            ],
        ),
    ]
