# Generated by Django 5.2.5 on 2025-10-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_customorder_contact_info_customorder_contact_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=500)),
                ('answer', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Short description of the rug (e.g., 'Blue Geometric Pattern Rug')", max_length=200)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('is_visible', models.BooleanField(default=True, help_text='Toggle to show this in the portfolio')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='portfolio/thumbnails/')),
            ],
            options={
                'verbose_name_plural': 'Portfolio Images',
                'db_table': 'portfolio images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='customorder',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
