# Generated by Django 5.2.5 on 2025-10-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_faqmodel_portfolioimage_alter_customorder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqmodel',
            options={'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Rug Properties'},
        ),
    ]
