# Generated by Django 5.2.5 on 2025-10-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_faqmodel_options_alter_property_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('content', models.TextField(max_length=4000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('links', models.CharField(blank=True)),
                ('tags', models.CharField(blank=True, choices=[('personal', 'Personal'), ('rug_making', 'Rug Making'), ('inspiration', 'Inspiration'), ('events', 'Events')])),
            ],
        ),
    ]
