# Generated by Django 5.2.5 on 2025-11-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='links',
            field=models.JSONField(blank=True, default=list, help_text="Insert links inside brackets []. Make sure links are seperated by commas and are within single quotes ('')"),
        ),
    ]
