# Generated by Django 5.2.5 on 2025-11-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
