# Generated by Django 5.2.5 on 2025-11-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_blogpost_content_alter_blogpost_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='links',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
