# Generated by Django 5.2.5 on 2025-11-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_blogpost_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('rug_making', 'Rug Making'), ('inspiration', 'Inspiration'), ('events', 'Events')], max_length=100),
        ),
    ]
