# Generated by Django 5.2.5 on 2025-11-15 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_blogpost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=300)),
                ('ticket_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(max_length=3000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('past', 'Past'), ('cancelled', 'Cancelled'), ('ongoing', 'Ongoing')], default='upcoming', max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('event_type', models.CharField(choices=[('online', 'Online'), ('workshop', 'Workshop'), ('meet-up', 'Meet-Up'), ('venue', 'Venue'), ('market', 'Market')], default='workshop', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event/')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='links',
            field=models.JSONField(blank=True, default=list, help_text='\n    1. Copy this: [{"title": "Link Name", "url": "https://..."}]\n    2. Change \'Link Name\' to your link\'s title\n    3. Change the URL to your actual link\n    4. Keep all punctuation exactly as shown\n    Example: [{\'title\': \'Dog Photo\', \'url\': \'https://unsplash.com/dog.jpg\'}]\n    '),
        ),
    ]
