# Generated by Django 5.2.5 on 2025-11-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_blogpost_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
