# Generated by Django 5.2.5 on 2026-04-06 17:01

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_newslettersubscriber_alter_customorderimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='blogs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='\n    Use this space to share news, stories, or insights about your rug-making journey.\n    For font styles use these method -> \n    1. Bold use **double asterisks**. \n    2. Italics use *single asterisks*. \n    3. Headings use ##Double Pound.\n    ', max_length=4000),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.CharField(choices=[('personal', 'Personal'), ('rug_making', 'Rug Making'), ('inspiration', 'Inspiration'), ('events', 'Events'), ('misc', 'Misc')], default='misc', max_length=100),
        ),
    ]
