# Generated by Django 5.2.5 on 2026-04-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_blogpost_image_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='quick_description',
            field=models.CharField(blank=True, help_text="A brief summary of the blog post (e.g., 'Sharing my latest rug-making project and inspiration.')", max_length=300, null=True),
        ),
    ]
