# Generated by Django 5.2.5 on 2026-04-21 22:12

import cloudinary_storage.storage
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_blogpost_quick_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AlterField(
            model_name='customorderimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='custom_orders/', validators=[main_app.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='customorderimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='custom_orders/thumbnails/', validators=[main_app.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='event/', validators=[main_app.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='portfolio/', validators=[main_app.models.validate_image_extension]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='products/thumbnails/', validators=[main_app.models.validate_image_extension]),
        ),
    ]
