# Generated by Django 5.2.5 on 2026-04-19 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_blogpost_quick_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text="The poll question (e.g., 'Which rug style do you prefer?')", max_length=300)),
                ('start_date', models.DateTimeField(help_text='When the poll should start')),
                ('end_date', models.DateTimeField(help_text='When the poll should end')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.OneToOneField(blank=True, help_text='Associate a poll with a blog post to gather reader feedback.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='main_app.blogpost')),
            ],
        ),
        migrations.CreateModel(
            name='PollChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_name', models.CharField(help_text="The text for this poll choice (e.g., 'Pokemon Art Style')", max_length=200)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='main_app.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=150)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main_app.pollchoice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.poll')),
            ],
            options={
                'unique_together': {('poll', 'session_key')},
            },
        ),
    ]
