# Generated by Django 5.2.5 on 2026-04-22 23:24

import cloudinary_storage.storage
import django.db.models.deletion
import main_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_delete_blogpost_alter_customorderimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Newsletter Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='newsletter/', validators=[main_app.models.validate_image_extension])),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='newsletter/thumbnails/', validators=[main_app.models.validate_image_extension])),
                ('link', models.URLField(blank=True, help_text='Makes this image clickable (e.g. product page, event link)', max_length=1000, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order in the newsletter. 0 is First, 1 is second, 2 is third, etc...')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main_app.newsletterpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
