# Generated by Django 5.2.5 on 2026-04-19 21:12

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_poll_pollchoice_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollchoice',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='polls/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='pollchoice',
            name='choice_name',
            field=models.CharField(max_length=200),
        ),
    ]
